### ISSUE TITLE
SQL EBMs

### ISSUE THREAD

**Issue by paulbkoch** [kaspersgit/ml_2_sql#1]
Hi @kaspersgit -- Thanks for making a utility that converts EBMs into SQL.  Would it be ok if we included a link to your repo in the TOOLs section of our README?

https://github.com/interpretml/interpret

**Comment by kaspersgit** [comment]
Hee @paulbkoch , great to hear you found my repo! I'm trying to constantly improve it whenever time but yes feel free to add a link to this repo.

**Comment by paulbkoch** [comment]
Great!  Does it currently work out of the box for standard binary/regression EBMs?  Should we tag it as experimental or something like that?

**Comment by paulbkoch** [comment]
Thanks!  It has been added.

**Comment by kaspersgit** [comment]
@paulbkoch after making some time to improve this utility it now works for EBM (and decision tree and lin/log regression) for regression, binary- and multiclass classification. Some tests are added to make sure a saved model file is converted into working SQL code
So in my humble opinion you can remove the 'experimental' tag!

**Comment by paulbkoch** [comment]
Thanks @kaspersgit!  I will do that.

**Comment by paulbkoch** [comment]
Done!  And thanks for adding EBMs to your package. It's really great that we can export EBMs to SQL reliably now!

**Comment by kaspersgit** [comment]
EBMs lend themselves very well for them to be written in SQL format because it is such an explainable model. Great work with it, using it whenever I can, still surprised how few people know about it!

**Comment by paulbkoch** [comment]
Thanks @kaspersgit.  It surprises me too.
